# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\ketanghuodong.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from ketanghuodong_test import TestCaseKetanghuodong

class KetanghuodongG(HttpRunner):

    config = (
        Config("教师创建课堂")
        .variables(HOST="${ENV(TestHOST)}")
        .base_url("${HOST}")
        .verify(False)
        .export(*[])
    )

    teststeps = [
        Step(
            RunTestCase('demo')
            .call(TestCaseKetanghuodong)
            .export("classroom_list")
        ),
        Step(
            RunRequest("获取课堂活动列表")
            .get(
                "/wisdomClassroom/getClassroomActivitys/${group_list($classroom_list,1)}"
            )
            .with_params(**{"pageSize": "999", "pageNum": "1"})
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        )
        
    ]


if __name__ == "__main__":
    KetanghuodongG().test_start()
