# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\jiaoshifaqidianming.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseJiaoshifaqidianming(HttpRunner):

    config = (
        Config("教师发布点名")
        .variables(HOST="${ENV(TestHOST)}",APPHOST="${ENV(TestHOSTAPP)}")
        .verify(False)
        .export(*[])
    )

    teststeps = [
        Step(
            RunRequest("/wisdomClassroom/getClassroomList")
            .get("${HOST}/wisdomClassroom/getClassroomList")
            .with_params(
                **{
                    "ocId": "${ENV(LoginNameCourseAdmin_ocId)}",
                    "classId": "",
                    "teacherId": "${ENV(LoginNameCourseAdmin_userid)}",
                    "status": "",
                    "pageNum": "1",
                    "pageSize": "10",
                    "lang": "zh",
                }
            )
            .with_headers(
                **{
                    "Authorization": "${ENV(LoginNameCourseAdmin_token)}",
                    "Content-Type": "application/json"
                }
            )
            .extract()
            .with_jmespath("body.list[0].id","classroomid")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/newAttendance/publishClassesAttendanceRecord")
            .post(
                "${APPHOST}/newAttendance/publishClassesAttendanceRecord"
            )
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}",
                    "Content-Type": "application/json;charset=UTF-8"
                }
            )
            .with_json(
                {
                    "userID": '${ENV(LoginNameCourseAdmin_userid)}',
                    "title": "%s 点名"%"${get_Nowtime()}",
                    "classID": ['${ENV(LoginNameCourseAdmin_class1)}', '${ENV(LoginNameCourseAdmin_class2)}', '${ENV(LoginNameCourseAdmin_class3)}'],
                    "time": -1,
                    "dist": 0,
                    "location": "",
                    "isGPS": False,
                    "webEnv": 1,
                    "type": 2,
                    "refreshCode": 1,
                    "refreshCodeTime": 15,
                    "draft": 0,
                    "classroomId": "${classroomid}",
                }
            )
            .extract()
            .with_jmespath("body.attendanceID","attendanceID")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/wisdomClassroom/getClassroomActivitys/1625")
            .get(
                "${HOST}/wisdomClassroom/getClassroomActivitys/${classroomid}"
            )
            .with_params(**{"relationType": "1", "pageSize": "999", "pageNum": "1"})
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/newAttendance/getAttendanceDataCode/${attendanceID}")
            .get("${APPHOST}/newAttendance/getAttendanceDataCode/${attendanceID}")
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseJiaoshifaqidianming().test_start()
