# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\ketanghuodong.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseKetanghuodong(HttpRunner):

    config = (
        Config("教师创建课堂")
        .variables(HOST="${ENV(TestHOST)}",relationType=0)
        .base_url("${HOST}")
        .verify(False)
        .export(*["classroom_list"])
    )

    teststeps = [
        Step(
            RunRequest("/wisdomClassroom/getClassroomList")
            .get("/wisdomClassroom/getClassroomList")
            .with_params(
                **{
                    "ocId": "${ENV(LoginNameCourseAdmin_ocId)}",
                    "classId": "",
                    "teacherId": "${ENV(LoginNameCourseAdmin_userid)}",
                    "status": "",
                    "pageNum": "1",
                    "pageSize": "10",
                    "lang": "zh",
                }
            )
            .with_headers(
                **{
                    "Authorization": "${ENV(LoginNameCourseAdmin_token)}",
                    "Content-Type": "application/json"
                }
            )
            .extract()
            .with_jmespath("body.list[0].id","classroomid")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取课堂信息")
            .get("/wisdomClassroom/getClassroomInfo/${classroomid}")
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
        ),
        Step(
            RunRequest("获取课堂活动列表")
            .get(
                "/wisdomClassroom/getClassroomActivitys/${classroomid}"
            )
            .with_params(**{"pageSize": "999", "pageNum": "1"})
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .extract()
            .with_jmespath("body.list","classroom_list")
            .validate()
            .assert_equal("status_code", 200)
        )
    ]


if __name__ == "__main__":
    TestCaseKetanghuodong().test_start()
