# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\zyuanliebiao.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseZyuanliebiao(HttpRunner):

    config = (
        Config("查看课堂资源")
        .variables(HOST="${ENV(TestHOST)}")
        .base_url("${HOST}")
        .verify(False)
        .export(*[])
    )

    teststeps = [
        Step(
            RunRequest("/wisdomClassroom/getClassroomList")
            .get("/wisdomClassroom/getClassroomList")
            .with_params(
                **{
                    "ocId": "${ENV(LoginNameCourseAdmin_ocId)}",
                    "classId": "",
                    "teacherId": "${ENV(LoginNameCourseAdmin_userid)}",
                    "status": "",
                    "pageNum": "1",
                    "pageSize": "10",
                    "lang": "zh",
                }
            )
            .with_headers(
                **{
                    "Authorization": "${ENV(LoginNameCourseAdmin_token)}",
                    "Content-Type": "application/json"
                }
            )
            .extract()
            .with_jmespath("body.list[0].id","classroomid")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/course/content")
            .get("/course/content")
            .with_params(
                **{
                    "ocId": "${ENV(LoginNameCourseAdmin_ocId)}",
                    "type": "",
                    "parentId": "0",
                    "teacherId": "${ENV(LoginNameCourseAdmin_userid)}",
                    "pn": "1",
                    "ps": "30",
                    "version": "2",
                }
            )
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取资源播放记录")
            .get("/wisdomClassroom/getResouceRecord")
            .with_params(**{"classroomId": "${classroomid}"})
            .with_headers(
                **{
                    "AUTHORIZATION": "${ENV(LoginNameCourseAdmin_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        
    ]


if __name__ == "__main__":
    TestCaseZyuanliebiao().test_start()
