# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\cktz.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCktz(HttpRunner):

    config = (
        Config("学生查看我的帖子")
        .variables(HOST="${ENV(TestHOST)}")
        .base_url("${HOST}")
        .verify(False)
        .export(*[])
    )

    teststeps = [
        
        Step(
            RunRequest("/forum/student/33988/7449241")
            .get("/forum/student/${ENV(stu001_ocId)}/${ENV(stu001_userid)}")
            .with_params(**{"pn": "1", "ps": "10"})
            .with_headers(
                **{
                    "Authorization": "${ENV(stu001_token)}",
                    "Content-Type": "application/json"
                }
            )
            .extract()
            .with_jmespath("body.studentForumDiscussionList[0].discussionId","discussionId")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/topic/selectInfo")
            .get("/topic/selectInfo")
            .with_params(**{"ocId": "${ENV(stu001_ocId)}", "discussionId": "", "type": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Authorization": "${ENV(stu001_token)}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/post/integral")
            .get("/post/integral")
            .with_params(**{"ocId": "${ENV(stu001_ocId)}", "discussionId": "$discussionId", "studentId": ""})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Authorization": "${ENV(stu001_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/topic/findStudentPost")
            .get("/topic/findStudentPost")
            .with_params(
                **{
                    "pn": "1",
                    "ps": "10",
                    "userId": "${ENV(stu001_userid)}",
                    "discussionId": "$discussionId",
                    "ocId": "${ENV(stu001_ocId)}",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Authorization": "${ENV(stu001_token)}"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseCktz().test_start()
