# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\jiaoshizhiding.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseJiaoshizhiding(HttpRunner):

    config = (
        Config("教师置顶讨论")
        .variables(HOST="${ENV(TestHOST)}")
        .base_url("${HOST}")
        .verify(False)
        .export(*[])
    )

    teststeps = [
        Step(
            RunRequest("/topic/selectInfo")
            .get("/topic/selectInfo")
            .with_params(**{"ocId": "${ENV(LoginNameCourseAdmin_ocId)}", "discussionId": "", "type": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Authorization": "${ENV(LoginNameCourseAdmin_token)}",
                }
            )
            .extract()
            .with_jmespath("body.result[0].id","discussionId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
        ),
        Step(
            RunRequest("/forum/topping")
            .put("/forum/topping")
            .with_params(
                **{"ocId": "${ENV(LoginNameCourseAdmin_ocId)}", "discussionId": "$discussionId", "type": "1", "lang": "zh"}
            )
            .with_headers(
                **{
                    "Authorization": "${ENV(LoginNameCourseAdmin_token)}",
                    "Content-Type": "application/json"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
        ),
        Step(
            RunRequest("/forum/topping")
            .put("/forum/topping")
            .with_params(
                **{"ocId": "${ENV(LoginNameCourseAdmin_ocId)}", "discussionId": "$discussionId", "type": "0", "lang": "zh"}
            )
            .with_headers(
                **{
                    "Authorization": "${ENV(LoginNameCourseAdmin_token)}",
                    "Content-Type": "application/json"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "成功")
        )
    ]


if __name__ == "__main__":
    TestCaseJiaoshizhiding().test_start()
