# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\xueshengtaolun.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseXueshengtaolun(HttpRunner):

    config = (
        Config("学生参与讨论")
        .variables(HOST="${ENV(TestHOST)}")
        .base_url("${HOST}")
        .verify(False)
        .export(*[])
    )

    teststeps = [

        Step(
            RunRequest("1")
            .get("/forum/student/${ENV(stu001_ocId)}/${ENV(stu001_userid)}")
            .with_params(**{"pn": "1", "ps": "10", "lang": "zh"})
            .with_headers(**{"Authorization": "${ENV(stu001_token)}","Content-Type": "application/json"})
            .extract()
            .with_jmespath("body.studentForumDiscussionList[0].discussionId","discussionId")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/topic/editTopicDetail")
            .get("/topic/editTopicDetail")
            .with_params(**{"ocId": "${ENV(stu001_ocId)}", "discussionId": "$discussionId"})
            .with_headers(**{"Authorization": "${ENV(stu001_token)}","Content-Type": "application/json"})
            .extract()
            .with_jmespath("body.result.forumId","forumId")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/topic/topicInfo")
            .get("/topic/topicInfo")
            .with_params(
                **{
                    "pn": "1",
                    "ps": "20",
                    "ocId": "${ENV(stu001_ocId)}",
                    "discussionId": "$discussionId",
                    "teacherId": "",
                    "classId": "",
                    "orderType": "",
                }
            )
            .with_headers(**{"Authorization": "${ENV(stu001_token)}","Content-Type": "application/json"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/topic/addViewCount")
            .post("/topic/addViewCount")
            .with_params(**{"discussionId": "$discussionId"})
            .with_headers(**{"Authorization": "${ENV(stu001_token)}","Content-Type": "application/json"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/topic/selectInfo")
            .get("/topic/selectInfo")
            .with_params(**{"ocId": "${ENV(stu001_ocId)}", "discussionId": "$discussionId", "type": "3"})
            .with_headers(**{"Authorization": "${ENV(stu001_token)}","Content-Type": "application/json"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/post/personReply")
            .post("/post/personReply")
            .with_headers(**{"Authorization": "${ENV(stu001_token)}","Content-Type": "application/json"})
            .with_json(
                {
                    "ocId": "${ENV(stu001_ocId)}",
                    "forumId": "$forumId",
                    "discussionId": "$discussionId",
                    "discussionType": 0,
                    "parentId": 0,
                    "attachments": [],
                    "message": "<p>测测测测测测测测测测测测测测测</p>\n",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseXueshengtaolun().test_start()
